### ISSUE TITLE
Feature-request: Add possibility to assert several fields of an object

### ISSUE THREAD

**Issue by Tradunsky** [memoizr/assertk-core#10]
A regular use case is when there is an actual object that state needs to be checked:
Person {
firstName,
lastName,
age
}
..

val person = SUT.<action>

expect that person isSuchThat {
  firstName isEqualTo "John"
  lastName isEqualTo "Doe"
  age isEqualTo 26
}

**Comment by sabiou** [comment]
I'm up for this

**Comment by memoizr** [comment]
This would be great however it's not possible to do in Kotlin

**Comment by Tradunsky** [comment]
Probably available alternative to that would be following:
expect that person isSuchThat {
  it.firstName isEqualTo "John"
  it.lastName isEqualTo "Doe"
  it.age isEqualTo 26
}
